import React, {useEffect, useRef, useState} from "react";
import {Bell, Check, Download, File, Hash, Image, Plus, Radio, RefreshCw, SlidersHorizontal, X} from "lucide-react";
import {app, call, extensions, RecordData as D} from "./bridge";
import {useNearViewport} from "./rich-content";
import {Select, DateField} from "./pickers";

export function TagEditor({value, change, disabled=false}: {value:string;change:(value:string)=>void;disabled?:boolean}) {
  const [text,setText]=useState("");
  const [known,setKnown]=useState<string[]>([]);
  const tags=Array.from(new Set(value.split(",").map(v=>v.trim().replace(/^#/,"")).filter(Boolean)));
  useEffect(()=>{call("manage_tags").then(v=>setKnown((v.items||[]).map((t:D)=>t.name||t.title).filter(Boolean))).catch(()=>{});},[]);
  const add=(raw=text)=>{const next=raw.split(/[,\s]+/).map(t=>t.replace(/^#/,"").trim()).filter(Boolean);change(Array.from(new Set([...tags,...next])).join(", "));setText("");};
  return <div className="tag-editor">
    <div className="tag-chips">{tags.map(t=><span key={t}>#{t}<button type="button" disabled={disabled} aria-label={`Remove tag ${t}`} onClick={()=>change(tags.filter(v=>v!==t).join(", "))}><X size={11}/></button></span>)}</div>
    <input aria-label="Add tag" placeholder="Add tag…" disabled={disabled} value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{if(text.trim())add();}} onKeyDown={e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();e.stopPropagation();add();}if(e.key==="Backspace"&&!text&&tags.length)change(tags.slice(0,-1).join(", "));}}/>
    {text&&<div className="tag-suggestions">{known.filter(t=>!tags.includes(t)&&t.toLowerCase().includes(text.toLowerCase())).slice(0,6).map(t=><button key={t} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>add(t)}>#{t}</button>)}</div>}
  </div>;
}

export function AttachmentGallery({item,run}: {item:D;run:(fn:()=>Promise<any>)=>any}) {
  const [images,setImages]=useState<Record<string,string>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[preview,setPreview]=useState<D|null>(null);
  const lightbox=useRef<HTMLDivElement>(null);
  const {ref: galleryRef, visible: nearViewport} = useNearViewport();
  useEffect(()=>{if(!preview)return;const previous=document.activeElement as HTMLElement;lightbox.current?.focus();return()=>previous?.focus();},[preview]);
  useEffect(()=>{let active=true;setErrors({});setImages({});
    if (!nearViewport) return;
    for(const a of item.attachments||[])if(a.type==="image"&&a.resourceUri)app.readServerResource({uri:a.resourceUri}).then(result=>{
      const c=result.contents[0];if(active&&"blob" in c)setImages(old=>({...old,[a.resourceUri]:`data:${c.mimeType};base64,${c.blob}`}));
    }).catch(()=>{if(active)setErrors(old=>({...old,[a.resourceUri]:a.resolved===false?"Not downloaded from iCloud":"Preview unavailable"}));});
    return()=>{active=false};
  },[item.id,item.revision,nearViewport]);
  const download=(index:number)=>run(async()=>{const value=await call("export_attachment",{reminderId:item.id,index});if(extensions.files)await extensions.files.open(value.path);});
  return <><div ref={galleryRef} className="attachment-gallery">{(item.attachments||[]).map((a:D,index:number)=><div className="attachment-tile" key={a.resourceUri||index}>
    <button className="attachment-preview" aria-label={`Preview ${a.filename||"attachment"}`} disabled={!images[a.resourceUri]} onClick={()=>setPreview({...a,index})}>
      {images[a.resourceUri]?<img src={images[a.resourceUri]} alt={a.filename||"Reminder image"}/>:<File size={28}/>}
    </button><div className="attachment-caption"><span title={a.filename}>{a.filename||"Attachment"}</span><button title="Save to Downloads" aria-label={`Download ${a.filename||"attachment"}`} onClick={()=>download(index)}><Download size={14}/></button></div>
    {errors[a.resourceUri]&&<small>{errors[a.resourceUri]}</small>}
  </div>)}</div>{preview&&<div ref={lightbox} className="image-lightbox" role="dialog" aria-modal="true" aria-label="Attachment preview" tabIndex={-1} onClick={()=>setPreview(null)} onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();setPreview(null);}if(e.key==="Tab"){e.preventDefault();const buttons=Array.from(lightbox.current?.querySelectorAll<HTMLButtonElement>('button')||[]);const index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(index+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus();}}}>
    <div className="lightbox-toolbar"><span>{preview.filename}</span><button onClick={e=>{e.stopPropagation();download(preview.index);}} aria-label="Download image"><Download size={18}/></button><button aria-label="Close image preview" onClick={()=>setPreview(null)}><X size={20}/></button></div>
    <img src={images[preview.resourceUri]} alt={preview.filename||"Attachment"} onClick={e=>e.stopPropagation()}/>
  </div>}</>;
}

const dateInput = (value:string) => /^\d{2}-\d{2}-\d{4}$/.test(value||"") ? value.split("-").reverse().join("-") : value||"";

const FAMILIES: Record<string,string>={flagged:"Flag",priorities:"Priority",hashtags:"Tags",date:"Date",time:"Time",lists:"List",location:"Location"};
const familyDefault=(family:string):any=>({flagged:true,priorities:["high"],hashtags:{hashtags:{operation:"or",include:[],exclude:[]}},date:{today:false},time:{morning:""},lists:{include:[],exclude:[]},location:{location:{title:"",latitude:0,longitude:0,radius:100,proximity:"enter"}}}[family]);

export function SmartListEditor({item,lists,symbols,busy,save}:any) {
  const [name,setName]=useState(item?.name||""),[color,setColor]=useState(item?.color?.hex||"#5394ed"),[emoji,setEmoji]=useState(item?.badge?.emoji||""),[symbol,setSymbol]=useState(item?.badge?.symbol||"default");
  const [filter,setFilter]=useState<D>(item?.filterJSON||{operation:"and",flagged:true}),[jsonMode,setJsonMode]=useState(false),[raw,setRaw]=useState(JSON.stringify(item?.filterJSON||{flagged:true},null,2));
  const [preview,setPreview]=useState<D|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const generation=useRef(0);
  const set=(key:string,value:any)=>{setFilter(old=>({...old,[key]:value}));setPreview(null);generation.current++;};
  const actual=()=>jsonMode?JSON.parse(raw):filter;
  const previewFilter=async()=>{setError("");setLoading(true);const current=++generation.current;try{const value=await call("preview_smart_filter",{filterJSON:actual()});if(generation.current===current)setPreview(value);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  const submit=()=>{try{const payload=actual();if(!name.trim()&&!item)throw Error("Give the smart list a name.");if(!Object.keys(payload).some(k=>k!=="operation"))throw Error("Add at least one filter.");save({...(item?{smart_list_id:item.id}:{name:name.trim()}),private:true,color,...(emoji?{emoji}:{symbol}),filter_json:JSON.stringify(payload)});}catch(e){setError((e as Error).message);}};
  return <div className="smart-editor">
    <div className="smart-identity"><span className="smart-avatar" style={{background:color}}>{emoji||<SlidersHorizontal size={23}/>}</span><div><input aria-label="Smart list name" placeholder="Smart list name" value={name} disabled={!!item} onChange={e=>setName(e.target.value)}/><div className="smart-appearance"><input type="color" aria-label="Smart list color" value={color} onChange={e=>setColor(e.target.value)}/><input aria-label="Smart list emoji" placeholder="Emoji" value={emoji} onChange={e=>setEmoji(e.target.value)}/><Select aria-label="Smart list symbol" value={symbol} disabled={!!emoji} onChange={e=>setSymbol(e.target.value)}>{Object.keys(symbols).map(s=><option key={s}>{s}</option>)}</Select></div></div></div>
    <div className="filter-mode"><span>Match</span><Select aria-label="Match filters" value={filter.operation||"and"} disabled={jsonMode} onChange={e=>set("operation",e.target.value)}><option value="and">all filters</option><option value="or">any filter</option></Select><button className="text-action" onClick={()=>{if(!jsonMode)setRaw(JSON.stringify(filter,null,2));else{try{setFilter(JSON.parse(raw));}catch{setError("Fix the JSON before switching to visual filters.");return;}}setJsonMode(!jsonMode);}}>{jsonMode?"Visual editor":"JSON"}</button></div>
    {jsonMode?<><textarea className="filter-json" aria-label="Smart filter JSON" value={raw} onChange={e=>{setRaw(e.target.value);setPreview(null);generation.current++;}} rows={14}/><p className="field-note">Uses Reminders’ filter format. Unsupported writes are rejected before saving.</p></>:<div className="filter-rows">{Object.entries(filter).filter(([key])=>key!=="operation").map(([key,value])=><div className="filter-row" key={key}>
      <div className="filter-row-heading"><strong>{FAMILIES[key]||key}</strong><button aria-label={`Remove ${FAMILIES[key]||key} filter`} onClick={()=>{const next={...filter};delete next[key];setFilter(next);setPreview(null);generation.current++;}}><X size={14}/></button></div>
      {key==="flagged"?<span className="field-note">Is flagged</span>:key==="priorities"?<div className="segmented-options">{["high","medium","low","none"].map(p=><button aria-pressed={value.includes(p)} key={p} onClick={()=>set(key,value.includes(p)?value.filter((v:string)=>v!==p):[...value,p])}>{p==="none"?"No priority":p}</button>)}</div>:key==="hashtags"?<>
        <Select aria-label="Tag rule" value={"any" in value?"any":"untagged" in value?"untagged":value.hashtags?.operation||"or"} onChange={e=>set(key,["any","untagged"].includes(e.target.value)?{[e.target.value]:""}:{hashtags:{operation:e.target.value,include:value.hashtags?.include||[],exclude:value.hashtags?.exclude||[]}})}><option value="or">Any selected tag</option><option value="and">All selected tags</option><option value="any">Any tag</option><option value="untagged">No tags</option></Select>
        {value.hashtags&&<><TagEditor value={value.hashtags.include.join(", ")} change={tags=>set(key,{hashtags:{...value.hashtags,include:tags.split(",").map(t=>t.trim()).filter(Boolean)}})}/><details className="filter-exclusions"><summary>Exclude tags{value.hashtags.exclude?.length?` · ${value.hashtags.exclude.length}`:""}</summary><TagEditor value={(value.hashtags.exclude||[]).join(", ")} change={tags=>set(key,{hashtags:{...value.hashtags,exclude:tags.split(",").map(t=>t.trim()).filter(Boolean)}})}/></details></>}
      </>:key==="date"?<><Select aria-label="Date rule" value={Object.keys(value)[0]} onChange={e=>set(key,{[e.target.value]:e.target.value==="today"?false:e.target.value==="dateRange"?["",""]:e.target.value==="relativeRange"?{direction:"inNext",magnitude:7,units:"day",includePastDue:false}:""})}><option value="any">Has a date</option><option value="noDate">No date</option><option value="today">Today</option><option value="relativeRange">Relative range</option><option value="onDate">On date</option><option value="beforeDate">Before date</option><option value="afterDate">After date</option><option value="dateRange">Between dates</option>{!["any","noDate","today","relativeRange","onDate","beforeDate","afterDate","dateRange"].includes(Object.keys(value)[0])&&<option value={Object.keys(value)[0]}>{Object.keys(value)[0]} · JSON</option>}</Select>
        {"relativeRange" in value?<><div className="relative-filter"><Select aria-label="Relative direction" value={value.relativeRange.direction} onChange={e=>set(key,{relativeRange:{...value.relativeRange,direction:e.target.value}})}><option value="inNext">In the next</option><option value="inPast">In the past</option></Select><input type="number" min="1" max="10000" aria-label="Relative amount" value={value.relativeRange.magnitude} onChange={e=>set(key,{relativeRange:{...value.relativeRange,magnitude:Number(e.target.value)}})}/><Select aria-label="Relative units" value={value.relativeRange.units} onChange={e=>set(key,{relativeRange:{...value.relativeRange,units:e.target.value}})}>{["minute","hour","day","week","month","year"].map(unit=><option key={unit} value={unit}>{unit}s</option>)}</Select></div>{value.relativeRange.direction==="inNext"&&<label className="inline-check"><input type="checkbox" checked={!!value.relativeRange.includePastDue} onChange={e=>set(key,{relativeRange:{...value.relativeRange,includePastDue:e.target.checked}})}/>Include overdue</label>}</>:"today" in value?<label className="inline-check"><input type="checkbox" checked={value.today} onChange={e=>set(key,{today:e.target.checked})}/>Include overdue</label>:"dateRange" in value?<div className="date-range">{[0,1].map(i=><DateField key={i} aria-label={i?"End date":"Start date"} value={dateInput(value.dateRange[i])} onChange={e=>{const dates=[...value.dateRange];dates[i]=e.target.value;set(key,{dateRange:dates});}}/>)}</div>:["onDate","beforeDate","afterDate"].includes(Object.keys(value)[0])?<DateField aria-label="Filter date" value={dateInput(Object.values(value)[0] as string)} onChange={e=>set(key,{[Object.keys(value)[0]]:e.target.value})}/>:null}
      </>:key==="time"?<Select aria-label="Time of day" value={Object.keys(value)[0]} onChange={e=>set(key,{[e.target.value]:""})}>{["morning","afternoon","evening","night","noTime"].map(v=><option key={v} value={v}>{v==="noTime"?"No time":v}</option>)}</Select>:key==="lists"?<div className="filter-lists">{lists.filter((l:D)=>!l.isGroup).map((l:D)=><label key={l.id}><span>{l.badge?.emoji||""} {l.title}</span><Select aria-label={`Filter ${l.title}`} value={value.include?.includes(l.objectUUID)?"include":value.exclude?.includes(l.objectUUID)?"exclude":"any"} onChange={e=>set(key,{...value,include:[...(value.include||[]).filter((id:string)=>id!==l.objectUUID),...(e.target.value==="include"?[l.objectUUID]:[])],exclude:[...(value.exclude||[]).filter((id:string)=>id!==l.objectUUID),...(e.target.value==="exclude"?[l.objectUUID]:[])]})}><option value="any">Any</option><option value="include">Include</option><option value="exclude">Exclude</option></Select></label>)}</div>:key==="location"?<>
        <Select aria-label="Location rule" value={value.vehicle||"location"} onChange={e=>set(key,e.target.value!=="location"?{vehicle:e.target.value}:familyDefault("location"))}><option value="location">At a location</option><option value="connected">Getting in the car</option><option value="disconnected">Getting out of the car</option></Select>
        {value.location?<div className="location-filter">{["title","latitude","longitude","radius"].map(k=><input key={k} aria-label={`Filter location ${k}`} type={k==="title"?"text":"number"} placeholder={k} value={value.location[k]} onChange={e=>set(key,{location:{...value.location,[k]:k==="title"?e.target.value:Number(e.target.value)}})}/>)}<Select aria-label="Location proximity" value={value.location.proximity} onChange={e=>set(key,{location:{...value.location,proximity:e.target.value}})}><option value="enter">Arriving</option><option value="leave">Leaving</option></Select></div>:<p className="field-note">Saved in Reminders. Local matching is unavailable because car-alarm metadata is not exposed.</p>}
      </>:<p className="field-note">Preserved. Edit this predicate in JSON.</p>}
    </div>)}</div>}
    {!jsonMode&&<Select className="add-filter" aria-label="Add filter" value="" onChange={e=>set(e.target.value,familyDefault(e.target.value))}><option value="">＋ Add filter</option>{Object.entries(FAMILIES).filter(([key])=>!(key in filter)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select>}
    {error&&<p role="alert" className="inline-error">{error}</p>}
    {preview&&<div className="filter-preview"><strong>{preview.total} matching reminders</strong>{preview.items.slice(0,5).map((i:D)=><div key={i.id}><span>{i.title}</span><small>{i.list}</small></div>)}</div>}
    <div className="editor-actions"><button disabled={loading||busy} onClick={previewFilter}>{loading?"Checking…":"Preview matches"}</button><button className="primary" disabled={busy||loading} onClick={submit}>{item?"Save smart list":"Create smart list"}</button></div>
  </div>;
}

export function EventActivity({listId,item,onWatch}:any) {
  const [data,setData]=useState<D|null>(null),[error,setError]=useState("");
  const [event,setEvent]=useState("reminder.completed"),[instruction,setInstruction]=useState("Summarize the change in one sentence.");
  const load=()=>call("event_activity").then(value=>{setData(value);setError("");}).catch(e=>setError(e.message));
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer);},[]);
  return <div className="event-activity"><div className="activity-heading"><Radio size={24}/><div><h2>Stay in the loop</h2><p>Connect reminder changes to ChatGPT.</p></div><button aria-label="Refresh event activity" onClick={load}><RefreshCw size={16}/></button></div>
    <div className="watch-composer"><label>When<Select aria-label="Event to monitor" value={event} onChange={e=>setEvent(e.target.value)}>{(data?.events||[]).map((e:D)=><option value={e.name} key={e.name}>{e.name.replace("reminder.","Reminder ").replace("list.","List ")}</option>)}</Select></label><label>Then<textarea aria-label="Event response instructions" value={instruction} onChange={e=>setInstruction(e.target.value)} rows={2}/></label><p className="field-note">{item?item.title:listId?"Current list":"All lists"} · Requires a host with MCP Events and this Mac running RemCTL.</p><button className="primary" disabled={!instruction.trim()||!data?.events?.length} onClick={()=>onWatch(`Subscribe to RemCTL's ${event} MCP event with arguments ${JSON.stringify(event==="list.updated"?(item?.listId||listId?{list_ids:[item?.listId||listId]}:{}):item?{reminder_ids:[item.id]}:listId?{list_ids:[listId]}:{})}. When an event arrives: ${instruction.trim()} Use the native MCP Events subscription. Do not create a polling automation. Report whether the host accepts the subscription.`)}>Set up in ChatGPT <Bell size={14}/></button></div>
    {error&&<p role="alert" className="inline-error">{error}</p>}
    <div className="activity-section"><h3>Subscriptions <small>{data?.subscriptions?.length||0}</small></h3>{data?.subscriptions?.length?data.subscriptions.map((s:D)=><div className="subscription-row" key={s.id}><span className={s.active?"live-dot":"paused-dot"}/><div><strong>{s.name}</strong><small>{s.destination} · {s.pending} pending</small>{s.lastError&&<small className="inline-error">{s.lastError}</small>}</div><span>{s.active?"Active":"Paused"}</span></div>):<p className="field-note">No active subscriptions. Set one up in a host that supports MCP Events.</p>}</div>
    <div className="activity-section"><h3>Recent deliveries</h3>{data?.recent?.length?data.recent.map((e:D)=><div className="delivery-row" key={e.eventId}><div><strong>{e.data.title}</strong><small>{e.name} · {new Date(e.timestamp).toLocaleTimeString()}</small></div><span className={e.delivery==="delivered"?"delivery-success":""}>{e.delivery}</span></div>):<p className="field-note">Delivered events will appear here.</p>}{data?.worker_error&&<p role="alert" className="inline-error">The last observation failed. No changes were inferred from an incomplete read.</p>}</div>
  </div>;
}
