import {build} from 'esbuild';
import assert from 'node:assert/strict';
const bundle=await build({entryPoints:[new URL('./src/reminder-helpers.ts',import.meta.url).pathname],bundle:true,write:false,format:'esm',platform:'node'});
const {arrangeReminders,selectionRange,rescheduledDue,recurrenceText,isReminder,notePresentation,todaySection,systemListVisible,pinnedSidebarLists}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
assert.equal(isReminder({id:9,title:'Groceries',isGroceries:true}),false);
assert.equal(isReminder({status:'ok',id:9}),false);
assert.equal(isReminder({id:9,title:'Milk',completed:false}),true);
const items=[{id:3,parentID:1,title:'child'},{id:2,title:'other'},{id:1,section:'Design',title:'parent'},{id:4,parentID:3,title:'grandchild'}];
assert.deepEqual(arrangeReminders(items).map(i=>[i.id,i.depth,i.groupSection]),[[2,0,undefined],[1,0,'Design'],[3,1,'Design'],[4,2,'Design']]);
assert.deepEqual(arrangeReminders(items,[1]).map(i=>i.id),[2,1]);
assert.deepEqual(arrangeReminders(items.filter(i=>i.id!==1)).map(i=>i.id),[3,4,2]);
assert.equal(arrangeReminders([{id:1,parentID:2},{id:2,parentID:1}]).length,2);
assert.deepEqual(selectionRange(arrangeReminders(items),1,4),[1,3,4]);
assert.deepEqual(selectionRange(items,null,2),[2]);
assert.equal(rescheduledDue({dueDate:'2026-09-30T14:30:00',allDay:false},'2026-10-02'),'2026-10-02 14:30');
assert.equal(rescheduledDue({dueDate:'2026-09-30T00:00:00',allDay:true},'2026-10-02'),'2026-10-02');
assert.equal(recurrenceText({frequency:'weekly',interval:2,daysOfWeek:[2,6]}),'weekly x2 mon,fri');
const ordinal={frequency:'monthly',interval:2,daysOfWeekDetailed:[{dayOfTheWeek:6,weekNumber:-1}],count:8};
assert.deepEqual(JSON.parse(recurrenceText(ordinal)),ordinal);
assert.deepEqual(notePresentation(JSON.stringify({changelog:'One\\nTwo',labels:'App Update',version:'5.0',app_url:'https://example.com'})), {text:'One\nTwo',label:'App Update',version:'5.0'});
assert.equal(notePresentation('{unusual note}').text,'{unusual note}');
assert.equal(todaySection({dueDate:'2026-09-30T14:00:00',allDay:false},'2026-09-30'),'Afternoon');
assert.equal(todaySection({dueDate:'2026-09-30T00:00:00',allDay:true},'2026-09-30'),'Today');
assert.equal(todaySection({dueDate:'2026-09-29T18:00:00',allDay:false},'2026-09-30'),'Overdue');
const nativeSmart = [{kind:'built-in',smartListType:'com.apple.reminders.smartlist.today'}, {kind:'built-in',smartListType:'com.apple.reminders.smartlist.flagged',pinnedDate:-63114076800,pinned:false}, {kind:'built-in',smartListType:'com.apple.reminders.smartlist.completed',pinned:true,pinnedDate:20}];
assert.equal(systemListVisible(nativeSmart,'today'),true);
assert.equal(systemListVisible(nativeSmart,'scheduled'),true);
assert.equal(systemListVisible(nativeSmart,'flagged'),false);
assert.equal(systemListVisible(nativeSmart,'completed'),true);
const pins = pinnedSidebarLists([{id:3,pinned:true,pinnedDate:30,parentListId:8},{id:1,pinned:true,pinnedDate:10},{id:8,isGroup:true,pinned:true},{id:4,pinned:false}], [{id:7,kind:'custom',pinned:true,pinnedDate:20},...nativeSmart]);
assert.deepEqual(pins.map(list=>[list.id,list.sidebarKind]),[[1,'list'],[7,'smart'],[3,'list']]);
console.log('Interaction contracts passed: hierarchy, collapse, range selection, calendar time preservation, recurrence fidelity.');
const {execFileSync}=await import('node:child_process');
const {OpenAIFormSchema,OpenAISettingsReadResultSchema,OpenAIUiToolMetadataSchema}=await import('@openai/mcp-extensions/server');
const contract=JSON.parse(execFileSync('python3',[new URL('../tests/export_desktop_contract.py',import.meta.url).pathname],{encoding:'utf8'}));
OpenAIFormSchema.parse(contract.form);
OpenAISettingsReadResultSchema.parse(contract.settings);
for(const tool of contract.tools) if(tool._meta?.['openai/ui']) OpenAIUiToolMetadataSchema.parse(tool._meta['openai/ui']);
console.log('OpenAI SDK contract validation passed: native rich forms, settings, and app entrypoints.');
